---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/tim-plan-schema.json
title: The dependencies table cell in tim list should show which dependencies
  are done or not
goal: ""
id: 38
uuid: 0d4e8db3-746d-45b9-9191-2d940602b36f
status: done
priority: low
createdAt: 2025-06-05T08:13:44.995Z
updatedAt: 2025-10-27T08:39:04.304Z
tasks: []
---
