---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/tim-plan-schema.json
title: "MCP Mode: Support repository exploration for planning/research"
goal: ""
id: 52
uuid: 61720b48-04ac-412c-a5f2-dc8952db127e
status: done
priority: low
dependencies:
  - 49
references:
  "49": fc084c7d-e293-4424-89f5-0d1e7b44ee2f
createdAt: 2025-06-07T02:13:21.632Z
updatedAt: 2025-10-27T08:39:04.275Z
tasks: []
---

Add MCP tools for repository exploration such as list/grep/read. Update the generate, prepare, and research commands
to take an --mcp flag which will add info to the prompt about appropriate MCP tools to use.
